In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\ASUS\Downloads\datasets\IMDB Dataset.csv")

In [3]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df['sentiment'].value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [5]:
df['sentiment'].value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [6]:
df.sample(1).values

array([['It\'s hard for me to explain this show to my grown friends. I have a bunch of Shasta Daisy\'s in the back yard which I lovingly call my "Chuckle Patch." My friends laugh at me and look at me like I have 2 heads. It would be great to see this series on DVD for us folks who remember it fondly with our other childhood memories, or to show our friends that there really WAS a chuckle patch! Where kids TV today is compiled of violent cartoons, characters who do magic, or a talking sponge who lives in a pineapple under the sea, The Magic Garden was real in the respect that it taught us good values.<br /><br />I will hold fond memories of Carole and Paula, and the Chuckle Patch.',
        'positive']], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
df['sentiment']=l.fit_transform(df['sentiment'])

In [8]:
df

review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]

In [9]:
from nltk.tokenize import word_tokenize

In [10]:
from nltk.corpus import stopwords

In [11]:
sw=stopwords.words('english')

In [12]:
import string
p=string.punctuation

In [13]:
len(sw)
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [14]:
len(p)

32

In [15]:
import emoji
def rem_special_char(x):
    text=''
    for i in x:
        if i.isalnum():
            text=text+i
        else:
            text=text+' '
    return text

In [16]:
import re
def remove_tags(x):
    pattern=re.compile('<.*>')
    return re.sub(pattern,'',x)

def rem_sw(x):
    l=[]
    for i in x:
        if i not in sw:
            l.append(i)
    return l

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

def stem_words(x):
    l=[]
    for i in x:
        l.append(ps.stem(i))
    return l

In [17]:
def preprocessing(text_low):
    
    text_no_tags=remove_tags(text_low)
    
    text_no_sc=rem_special_char(text_no_tags)
    
    tokens=word_tokenize(text_no_sc)
    
    tokens_no_sw=rem_sw(tokens)
    
    tokens_stem=stem_words(tokens_no_sw)
    
    return tokens_stem
    
    

In [18]:
df['text_lower']=df['review'].apply(lambda x: x.lower())
df['text']=df['text_lower'].apply(preprocessing)

In [19]:
df

review  sentiment  \
0      One of the other reviewers has mentioned that ...          1   
1      A wonderful little production. <br /><br />The...          1   
2      I thought this was a wonderful way to spend ti...          1   
3      Basically there's a family where a little boy ...          0   
4      Petter Mattei's "Love in the Time of Money" is...          1   
...                                                  ...        ...   
49995  I thought this movie did a down right good job...          1   
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0   
49997  I am a Catholic taught in parochial elementary...          0   
49998  I'm going to have to disagree with the previou...          0   
49999  No one expects the Star Trek movies to be high...          0   

                                              text_lower  \
0      one of the other reviewers has mentioned that ...   
1      a wonderful little production. <br /><br />the...   
2      i thought this was a wonderful way to spend ti...   
3      basically there's a family where a little boy ...   
4      petter mattei's "love in the time of money" is...   
...                                                  ...   
49995  i thought this movie did a down right good job...   
49996  bad plot, bad dialogue, bad acting, idiotic di...   
49997  i am a catholic taught in parochial elementary...   
49998  i'm going to have to disagree with the previou...   
49999  no one expects the star trek movies to be high...   

                                                    text  
0      [one, review, mention, watch, 1, oz, episod, h...  
1      [wonder, littl, product, realism, realli, come...  
2      [thought, wonder, way, spend, time, hot, summe...  
3      [basic, famili, littl, boy, jake, think, zombi...  
4      [petter, mattei, love, time, money, visual, st...  
...                                                  ...  
49995  [thought, movi, right, good, job, creativ, ori...  
49996  [bad, plot, bad, dialogu, bad, act, idiot, dir...  
49997  [cathol, taught, parochi, elementari, school, ...  
49998  [go, disagre, previou, comment, side, maltin, ...  
49999  [one, expect, star, trek, movi, high, art, fan...  

[50000 rows x 4 columns]

In [20]:
new_df=df[['text','sentiment']]

In [21]:
new_df

text  sentiment
0      [one, review, mention, watch, 1, oz, episod, h...          1
1      [wonder, littl, product, realism, realli, come...          1
2      [thought, wonder, way, spend, time, hot, summe...          1
3      [basic, famili, littl, boy, jake, think, zombi...          0
4      [petter, mattei, love, time, money, visual, st...          1
...                                                  ...        ...
49995  [thought, movi, right, good, job, creativ, ori...          1
49996  [bad, plot, bad, dialogu, bad, act, idiot, dir...          0
49997  [cathol, taught, parochi, elementari, school, ...          0
49998  [go, disagre, previou, comment, side, maltin, ...          0
49999  [one, expect, star, trek, movi, high, art, fan...          0

[50000 rows x 2 columns]

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
cv=CountVectorizer(max_features=2000)

In [24]:
new_df['text']=new_df['text'].apply(lambda x: ''.join(x))
X=cv.fit_transform(new_df['text']).toarray()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11968\4211132897.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['text']=new_df['text'].apply(lambda x: ''.join(x))


In [25]:
X.shape

(50000, 2000)

In [26]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
y=new_df['sentiment']

In [28]:
y.shape

(50000,)

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [31]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

In [32]:
m1=GaussianNB()
m2=MultinomialNB()
m3=BernoulliNB()

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
m1.fit(X_train,y_train)
m2.fit(X_train,y_train)
m3.fit(X_train,y_train)

BernoulliNB()

In [35]:
y_pred1=m1.predict(X_test)
y_pred2=m2.predict(X_test)
y_pred3=m3.predict(X_test)

In [36]:
confusion_matrix_1=confusion_matrix(y_test,y_pred1)

In [37]:
confusion_matrix_1

array([[ 105, 4856],
       [   0, 5039]], dtype=int64)

In [38]:
confusion_matrix_2=confusion_matrix(y_test,y_pred2)

In [39]:
confusion_matrix_2

array([[4772,  189],
       [4825,  214]], dtype=int64)

In [40]:
confusion_matrix_3=confusion_matrix(y_test,y_pred3)

In [41]:
confusion_matrix_3

array([[ 105, 4856],
       [   0, 5039]], dtype=int64)

In [42]:
from sklearn.metrics import accuracy_score
a1=accuracy_score(y_test,y_pred1)
a2=accuracy_score(y_test,y_pred2)
a3=accuracy_score(y_test,y_pred3)

In [43]:
pd.DataFrame({'Model':['m1','m2','m3'],'Accuracy':[a1,a2,a3]})

Model  Accuracy
0    m1    0.5144
1    m2    0.4986
2    m3    0.5144